### ISSUE TITLE
It don't works when I build a new file.

### ISSUE THREAD

**Issue by caijiMK** [absop/RainbowBrackets#26]
When I build a new file and save it with `.json` suffix, Rainbowbrackets don't works.  
![](https://user-images.githubusercontent.com/60387408/200809272-88a2abd6-3e45-426d-9617-4d91569e34fd.png)

**Comment by absop** [comment]
Your JSON file format is invalid!

In the default settings of RB for JSON format files, the round bracket '(' is not included in the bracket set, there are only square bracket '[' and curly bracket '{'.

**Comment by caijiMK** [comment]
But I have added parentheses to the bracket set set in the user setting!It's my user setting:

Sorry,my English is not very good.








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [absop/RainbowBrackets] It don&#39;t works when I build a new file. (Issue #26)





 
Your JSON file format is invalid!
 
In the default settings of RB for JSON format files, the round bracket '(' is not included in the bracket set, there are only square bracket '[' and curly bracket '{'.

**Comment by absop** [comment]
Have you reload the file after you add it to your setting for JSON?

Could you put your settings here (with markdown syntax highlighting)?

**Comment by caijiMK** [comment]
Yes.And&nbsp;I've restarted Sublime many times.But every time I build a new file and save it,the package doesn't work.I must Enter "RainbowBrackets: Make Rainbow"command.This is my setting.


Can I speak Chinese?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "absop/RainbowBrackets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [absop/RainbowBrackets] It don't works when I build a new file. (Issue #26)





 
Have you reload the file after you add it to your setting for JSON?
 
Could you put your settings here (with markdown syntax highlighting)?

**Comment by absop** [comment]
可以

**Comment by caijiMK** [comment]
所以是什么问题呢？我重启过很多次Sublime了，但是每次新建文件夹然后保存都不会渲染彩虹括号。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "absop/RainbowBrackets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [absop/RainbowBrackets] It don't works when I build a new file. (Issue #26)





 
可以

**Comment by absop** [comment]
可以建议你换其它语法试试，至于你想在JSON里面高亮圆括号的问题，我晚上看看

**Comment by caijiMK** [comment]
哦其实我用 JSON 演示只是为了方便点（不想写大段英语）。实际上我平时写的是C++，结果也还是无法显示高亮。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "absop/RainbowBrackets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午3:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [absop/RainbowBrackets] It don't works when I build a new file. (Issue #26)





 
可以建议你换其它语法试试，至于你想在JSON里面高亮圆括号的问题，我晚上看看

**Comment by absop** [comment]
注意一下`coloring`这个选项。

https://github.com/absop/RainbowBrackets/blob/master/RainbowBrackets.sublime-settings#L11-L13

**Comment by caijiMK** [comment]
解决了，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [absop/RainbowBrackets] It don&#39;t works when I build a new file. (Issue #26)





 
注意一下coloring这个选项。
 
https://github.com/absop/RainbowBrackets/blob/master/RainbowBrackets.sublime-settings#L11-L13

**Comment by absop** [comment]
不客气，`enable`用于控制是否查找提取括号，`coloring`用于控制是否高亮括号。因为RB不仅可以高亮括号，还提供了一些括号编辑操作，所以这两个选项都是有用的。

**Comment by caijiMK** [comment]
嗯，明白了，十分感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [absop/RainbowBrackets] It don&#39;t works when I build a new file. (Issue #26)





 
不客气，enable用于控制是否查找提取括号，coloring用于控制是否高亮括号。因为RB不仅可以高亮括号，还提供了一些括号编辑操作，所以这两个选项都是有用的。
